rancher:
  environment:
    CALICO_LIBNETWORK_CREATE_PROFILES: true
    CALICO_LIBNETWORK_LABEL_ENDPOINTS: true
    CALICO_LIBNETWORK_IFPREFIX: cali
    CALICO_LIBNETWORK_ENABLED: true
    CALICO_NETWORKING_BACKEND: bird
    IP_AUTODETECTION_METHOD: first-found
    IP6_AUTODETECTION_METHOD: first-found
    ETCD_ENDPOINTS: http://192.168.99.103:2379
    ETCD_LISTEN_CLIENT_URLS: http://192.168.99.103:2379
    ETCD_INITIAL_CLUSTER: "rancher-01=http://192.168.99.100:2380,rancher-02=http://192.168.99.101:2380,rancher-03=http://192.168.99.102:2380"
    MESOS_PORT: 5050
    MESOS_IP: 192.168.99.103
    MESOS_LOG_DIR: /var/log/mesos
    MESOS_WORK_DIR: /var/tmp/mesos
    MESOS_MASTER: "zk://192.168.99.100:2181,192.168.99.101:2181,192.168.99.102:2181/mesos"
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_SWITCH_USER: false
