rancher:
  environment:
    CALICO_LIBNETWORK_CREATE_PROFILES: true
    CALICO_LIBNETWORK_LABEL_ENDPOINTS: true
    CALICO_LIBNETWORK_IFPREFIX: cali
    CALICO_LIBNETWORK_ENABLED: true
    CALICO_NETWORKING_BACKEND: bird
    IP_AUTODETECTION_METHOD: first-found
    IP6_AUTODETECTION_METHOD: first-found
    ETCD_ADVERTISE_CLIENT_URLS: http://192.168.99.100:2379
    ETCD_ENDPOINTS: http://192.168.99.100:2379,http://192.168.99.101:2379,http://192.168.99.102:2379
    ETCD_DATA_DIR: /opt/etcd/data
    ETCD_LISTEN_CLIENT_URLS: http://192.168.99.100:2379
    ETCD_LISTEN_PEER_URLS: http://192.168.99.100:2380
    ETCD_INITIAL_CLUSTER: "rancher-01=http://192.168.99.100:2380,rancher-02=http://192.168.99.101:2380,rancher-03=http://192.168.99.102:2380"
    ETCD_INITIAL_ADVERTISE_PEER_URLS: http://192.168.99.100:2380
    ETCD_NAME: rancher-01
    ETCD_PEER_AUTO_TLS: false
    ETCD_AUTO_TLS: false
